apiVersion: apps/v1
kind: Deployment
metadata:
  name: socks-shop-app
  labels:
    app: socks-shop-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: socks-shop-app 
  template:
    metadata:
      labels:
        app: socks-shop-app
    spec:
    containers:
    - name: socks-shop-app
      image: my-docker-registry/socks-shop:latest
      ports:
      - containerPort: 80
      env:
      - name: ENV_VAR_NAME
        value: "value"

