apiVersion: v1
kind: Service
metadata:
  name: socks-shop-app
spec:
  selector:
    app: socks-shop-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
